version: "3.7"

services:
    flask:
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: unless-stopped
        ports:
            - 8000:8000
        volumes:
            - "./data/:/app/data"
        #env_file:
        #    - ../.env
