name: pa
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pillow
  - numpy
  - pandas
  - numba
  - mercantile
  - datashader
  - gunicorn
  - pyarrow
  - fastparquet
  - spatialpandas
  - shapely
  - geopandas
  - Flask
  - pip:
    - python-dotenv==0.14.0
    - git+https://github.com/CartoDB/python-quadkey.git
    - python-geohash==0.8.5
