name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pillow
  - numpy
  - pandas
  - datashader
  - gunicorn
  - pyarrow
  - Flask
  - pip:
    - python-dotenv==0.14.0
    - git+https://github.com/CartoDB/python-quadkey.git
