name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pillow
  - numpy
  - pandas
  - numba
  - mercantile
  - datashader
  - gunicorn
  - pyarrow
  - geopandas==0.9.0
  - pygeos
  - Flask
  - pip:
    - python-dotenv==0.14.0
